### ISSUE TITLE
Final draft review (before submission)

### ISSUE THREAD

**Issue by smpark7** [arfc/2021-park-moltres-benchmark#11]
This issue can be closed when @munkm has reviewed the final draft linked below, and I have integrated her review comments after.

[main.pdf](https://github.com/arfc/2021-park-moltres-benchmark/files/7323582/main.pdf)

**Comment by munkm** [comment]
Here you go! 
[park_final.pdf](https://github.com/arfc/2021-park-moltres-benchmark/files/7523431/park_final.pdf)
