### ISSUE TITLE
Review of revised manuscript

### ISSUE THREAD

**Issue by smpark7** [arfc/2021-park-moltres-benchmark#17]
@munkm The revised manuscript is now ready for review.

Revised manuscript: [revised.pdf](https://github.com/arfc/2021-park-moltres-benchmark/files/8137396/revised.pdf)
Review comments and replies: [revise.pdf](https://github.com/arfc/2021-park-moltres-benchmark/files/8137399/revise.pdf)

**Comment by gwenchee** [comment]
@smpark7 When you submit the paper, do you intend to send a marked up version which reflects the changes you made? I remember i did that for the ddca paper

**Comment by smpark7** [comment]
@gwenchee That would be useful. Is there a better way to do that than latexdiff?

**Comment by munkm** [comment]
I have heard good things about `git-latexdiff` for the git support.

**Comment by gwenchee** [comment]
I'm not sure what I used. But, I remember it being quite low effort.

**Comment by smpark7** [comment]
@munkm Here's my git-latexdiff output. It worked this time without any issues!

[latexdiff.pdf](https://github.com/arfc/2021-park-moltres-benchmark/files/8164388/latexdiff.pdf)

**Comment by munkm** [comment]
Excellent!!! Thanks @smpark7!

**Comment by smpark7** [comment]
@munkm In addition to the changes I've made, please let me know whether I should:
1. Include an outline paragraph at the end of the introduction section (e.g. something like "The outline of this paper is as follows: Section 2 describes ...")
2. Rename the "Results" section to "Results and Discussion"

**Comment by munkm** [comment]
I think this is closed now!
