### ISSUE TITLE
Make edits based on Nathan's review comments

### ISSUE THREAD

**Issue by smpark7** [arfc/2021-park-moltres-benchmark#5]
This issue can be closed when @smpark7 makes the recommended changes from @nsryan2's review of the first draft.

Two-column version: [park-two-column.pdf](https://github.com/arfc/2021-park-moltres-benchmark/files/6634170/park-two-column.pdf)

One-column version: [park-one-column.pdf](https://github.com/arfc/2021-park-moltres-benchmark/files/6634172/park-one-column.pdf)

Feel free to attach your review comments here after you're done @nsryan2. Thanks!

**Comment by nsryan2** [comment]
[park-two-column 2.pdf](https://github.com/arfc/2021-park-moltres-benchmark/files/6650718/park-two-column.2.pdf)
I tried to keep text edits in red and suggestions in blue, let me know if there's anything I can clarify or help out with!

**Comment by smpark7** [comment]
Thanks @nsryan2!
