### ISSUE TITLE
Make edits based on Dr Munk's review of the second draft

### ISSUE THREAD

**Issue by smpark7** [arfc/2021-park-moltres-benchmark#8]
This issue can be closed when @smpark7 makes the recommended changes from @munkm's review of the second draft (linked pdfs below).

Two-column version: [two-column-park.pdf](https://github.com/arfc/2021-park-moltres-benchmark/files/6711276/two-column-park.pdf)

One-column version: [one-column-park.pdf](https://github.com/arfc/2021-park-moltres-benchmark/files/6711280/one-column-park.pdf)

**Comment by katyhuff** [comment]
[one-column-park.pdf](https://github.com/arfc/2021-park-moltres-benchmark/files/6795516/one-column-park.pdf)

**Comment by munkm** [comment]
Here are my review comments [one-column-park.pdf](https://github.com/arfc/2021-park-moltres-benchmark/files/7155535/one-column-park.2.pdf)
